// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAidXO1Ayi1PQPe1hc3H7HXqh57CwLVCeI',
    appId: '1:397080082367:web:87567ab232df2e2835d30a',
    messagingSenderId: '397080082367',
    projectId: 'movie-4b2a8',
    authDomain: 'movie-4b2a8.firebaseapp.com',
    storageBucket: 'movie-4b2a8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxME-JTsa2H6ypi1ii5VJ9kfXNxnAf_aI',
    appId: '1:397080082367:android:9775fcfd421a498835d30a',
    messagingSenderId: '397080082367',
    projectId: 'movie-4b2a8',
    storageBucket: 'movie-4b2a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwnujfauVwlqZc63lfEPWYv2cn3b44fMA',
    appId: '1:397080082367:ios:03c886bfb877be8435d30a',
    messagingSenderId: '397080082367',
    projectId: 'movie-4b2a8',
    storageBucket: 'movie-4b2a8.appspot.com',
    iosBundleId: 'com.example.flutterProjectCep',
  );
}
